numServers: 3
numClients: 1

debug: true

clientRequestTimeout: 5s

fd:
  pullInterval: 200ms
  timeout: 100ms

mailboxes:
  receiveChanSize: 10000
  dialTimeout: 50ms
  readTimeout: 1ms
  writeTimeout: 50ms

leaderElection:
  timeout: 150ms
  timeoutOffset: 150ms

appendEntriesSendInterval: 2ms

sharedResourceTimeout: 1ms

inputChanReadTimeout: 1ms

servers:
  1:
    raftAddr: "localhost:8001"
    kvAddr: "localhost:9001"
    monitorAddr: "localhost:10001"

  2:
    raftAddr: "localhost:8002"
    kvAddr: "localhost:9002"
    monitorAddr: "localhost:10002"
  
  3:
    raftAddr: "localhost:8003"
    kvAddr: "localhost:9003"
    monitorAddr: "localhost:10003"
  
clients:
  1:
    mailboxAddr: "localhost:8019"
  
  # 2:
  #   mailboxAddr: "localhost:8020"
  
  # 3:
  #   mailboxAddr: "localhost:8021"

  # 4:
  #   mailboxAddr: "localhost:8022"
  
  # 5:
  #   mailboxAddr: "localhost:8023"
  
  # 6:
  #   mailboxAddr: "localhost:8024"

  # 7:
  #   mailboxAddr: "localhost:8025"
  
  # 8:
  #   mailboxAddr: "localhost:8026"
